import { Project } from '../../projects/project.type';

export const projectsSeed: Omit<Project, 'id'>[] = [
  {
    name: 'StopJudol Youtube Bot',
    date: '2025-09-01',
    description: 'StopJudol is a web dashboard, similar to YouTube Studio, that integrates the YouTube Data API with a fine‑tuned BERT model (~99% accuracy) to automatically detect online‑gambling promotions in YouTube comments. It empowers content creators to clean up their comment sections effortlessly in just two steps: run the detection and bulk-delete flagged comments.',
    technologies: [
      { name: 'Python',     iconClass: 'devicon-python-plain colored text-3xl' },
      { name: 'TypeScript', iconClass: 'devicon-typescript-plain colored text-3xl' },
      { name: 'FastAPI',    iconClass: 'devicon-fastapi-plain colored text-3xl' },
      { name: 'React',      iconClass: 'devicon-react-original colored text-3xl' },
      { name: 'PostgreSQL', iconClass: 'devicon-postgresql-plain colored text-3xl' },
      { name: 'Redis',      iconClass: 'devicon-redis-plain colored text-3xl' },
      { name: 'PyTorch',    iconClass: 'devicon-pytorch-original colored text-3xl' },
      { name: 'Pandas',     iconClass: 'devicon-pandas-plain colored text-3xl' },
    ],
    role: ['Full-Stack Developer', 'Machine Learning Engineer'],
    category: ['Web', 'ML'],
    githubUrl: 'https://github.com/bwbayu/youtube-bot',
  },
  {
    name: 'Qlassroom',
    date: '2025-09-01',
    description: 'A multi-modal classroom assistant that captures speech, video, slides, images, and documents together into a searchable knowledge memory. Awarded in Qdrant Hackathon 2025 Project by YHHA (Best in Category TwelveLabs)',
    technologies: [
      { name: 'Python',                       iconClass: 'devicon-python-plain colored text-3xl' },
      { name: 'Google Cloud Platform (GCP)',   iconClass: 'devicon-googlecloud-plain colored text-3xl' },
      { name: 'Cognee',     iconImage: '/icons/skills/cognee.png' },
      { name: 'Qdrant',     iconImage: '/icons/skills/qdrant.webp' },
      { name: 'TwelveLabs', iconImage: '/icons/skills/twelvelabs.jpg' },
      { name: 'CrewAI',     iconImage: '/icons/skills/crewai.png' },
      { name: 'Gradio',     iconImage: '/icons/skills/gradio.png' },
    ],
    role: ['AI Engineer'],
    category: ['Web', 'ML'],
    githubUrl: 'https://github.com/bwbayu/Qlassroom',
  },
  {
    name: 'RAG Chatbot CSE UPI',
    date: '2025-08-01',
    description: 'A lightweight RAG-based chatbot built with FastAPI and Streamlit to answer questions about the Faculty of Computer Science Education at UPI, using content sourced from the official website.',
    technologies: [
      { name: 'FastAPI',                      iconClass: 'devicon-fastapi-plain colored text-3xl' },
      { name: 'Python',                       iconClass: 'devicon-python-plain colored text-3xl' },
      { name: 'Docker',                       iconClass: 'devicon-docker-plain colored text-3xl' },
      { name: 'Google Cloud Platform (GCP)',   iconClass: 'devicon-googlecloud-plain colored text-3xl' },
      { name: 'LangChain', iconImage: '/icons/skills/langchain.png' },
      { name: 'Pinecone',  iconImage: '/icons/skills/pinecone.png' },
      { name: 'Streamlit',                    iconClass: 'devicon-streamlit-plain colored text-3xl' },
    ],
    role: ['Full-Stack Developer', 'Machine Learning Engineer'],
    category: ['Web', 'ML'],
    url:       'https://chatbot-upi.bwbayu.space/',
    githubUrl: 'https://github.com/bwbayu/RAG_Chatbot',
  },
  {
    name: 'Thesis Code - ASAS Model Development & Demo Web',
    date: '2025-01-01',
    description: 'A full-stack project for developing and deploying an Automatic Short Answer Scoring (ASAS) system using BERT-based models, combining machine learning experimentation with a web-based demo interface.',
    technologies: [
      { name: 'PyTorch',                      iconClass: 'devicon-pytorch-original colored text-3xl' },
      { name: 'Python',                       iconClass: 'devicon-python-plain colored text-3xl' },
      { name: 'Numpy',                        iconClass: 'devicon-numpy-plain colored text-3xl' },
      { name: 'Pandas',                       iconClass: 'devicon-pandas-plain colored text-3xl' },
      { name: 'React',                        iconClass: 'devicon-react-original colored text-3xl' },
      { name: 'Docker',                       iconClass: 'devicon-docker-plain colored text-3xl' },
      { name: 'Flask',                        iconClass: 'devicon-flask-original colored text-3xl' },
      { name: 'Google Cloud Platform (GCP)',   iconClass: 'devicon-googlecloud-plain colored text-3xl' },
    ],
    role: ['Full-Stack Developer', 'Machine Learning Engineer'],
    category: ['Web', 'ML'],
    url:       'https://asas-demo.web.app/',
    githubUrl: 'https://github.com/bwbayu/thesis-code',
  },
  {
    name: 'KostHub',
    date: '2025-02-01',
    description: 'Participated as Machine Learning Engineer in Mapid WebGIS Competition 2025. Built a price prediction model (XGBoost, R² = 0.82) and a boarding house recommender system (KNN). Deployed models into the system using FastAPI.',
    technologies: [
      { name: 'FastAPI',      iconClass: 'devicon-fastapi-plain colored text-3xl' },
      { name: 'Python',       iconClass: 'devicon-python-plain colored text-3xl' },
      { name: 'Numpy',        iconClass: 'devicon-numpy-plain colored text-3xl' },
      { name: 'Pandas',       iconClass: 'devicon-pandas-plain colored text-3xl' },
      { name: 'Scikit-Learn', iconClass: 'devicon-scikitlearn-plain colored text-3xl' },
    ],
    role: ['Machine Learning Engineer'],
    category: ['Data/ML'],
  },
  {
    name: 'Jenkins Pipeline',
    date: '2025-01-01',
    description: 'Part of the Dicoding IDCamp DevOps Engineer scholarship, where I implemented a CI/CD pipeline using Jenkins, Docker, and AWS EC2 to automate the build, test, and deployment process for a React and Python app. Additionally, integrated Prometheus and Grafana for real-time monitoring and visualization of metrics.',
    technologies: [
      { name: 'Amazon Web Services (AWS)', iconClass: 'devicon-amazonwebservices-plain-wordmark colored text-3xl' },
      { name: 'Docker',                    iconClass: 'devicon-docker-plain colored text-3xl' },
      { name: 'Jenkins',                   iconClass: 'devicon-jenkins-plain colored text-3xl' },
      { name: 'Prometheus',                iconClass: 'devicon-prometheus-original colored text-3xl' },
      { name: 'Grafana',                   iconClass: 'devicon-grafana-plain colored text-3xl' },
    ],
    role: ['DevOps Engineer'],
    category: ['Web'],
    githubUrl: 'https://github.com/bwbayu/jenkins-pipeline',
  },
  {
    name: 'Forum API',
    date: '2024-10-01',
    description: 'Part of Dicoding AWS Back-End Developer Academy scholarship, this API was designed for a discussion platform using Clean Architecture and TDD. Features unit, integration, and functional testing, CI/CD with GitHub Actions, and secure deployment on AWS.',
    technologies: [
      { name: 'Amazon Web Services (AWS)', iconClass: 'devicon-amazonwebservices-plain-wordmark colored text-3xl' },
      { name: 'PostgreSQL',                iconClass: 'devicon-postgresql-plain colored text-3xl' },
      { name: 'Node.js',                   iconClass: 'devicon-nodejs-plain-wordmark colored text-3xl' },
      { name: 'JavaScript',                iconClass: 'devicon-javascript-plain colored text-3xl' },
    ],
    role: ['Back-End Developer'],
    category: ['Web'],
    githubUrl: 'https://github.com/bwbayu/forum-api',
  },
  {
    name: 'Product Clustering and Recommendation System',
    date: '2024-11-01',
    description: 'Developed for the Hology Data Mining 2024 Final. Using TF-IDF, SentenceTransformer, and POS tagging, improved product discoverability by clustering over 516 categories and building a recommendation system to enhance user experience.',
    technologies: [
      { name: 'Python',       iconClass: 'devicon-python-plain colored text-3xl' },
      { name: 'Numpy',        iconClass: 'devicon-numpy-plain colored text-3xl' },
      { name: 'Pandas',       iconClass: 'devicon-pandas-plain colored text-3xl' },
      { name: 'Scikit-Learn', iconClass: 'devicon-scikitlearn-plain colored text-3xl' },
    ],
    role: ['Data Scientist'],
    category: ['Data/ML'],
    githubUrl: 'https://github.com/bwbayu/product_name_clustering',
  },
  {
    name: 'Clothing Multi-Label Classification',
    date: '2024-10-01',
    description: 'Developed for the Hology Data Mining 2024 Preliminary. Fine-tuned a Vision Transformer (ViT) for multi-label classification to predict clothing type and color. Achieved an Exact Match Ratio (EMR) of 0.9829, securing a top-8 position out of 196 teams.',
    technologies: [
      { name: 'PyTorch',      iconClass: 'devicon-pytorch-original colored text-3xl' },
      { name: 'Python',       iconClass: 'devicon-python-plain colored text-3xl' },
      { name: 'Numpy',        iconClass: 'devicon-numpy-plain colored text-3xl' },
      { name: 'Pandas',       iconClass: 'devicon-pandas-plain colored text-3xl' },
      { name: 'Scikit-Learn', iconClass: 'devicon-scikitlearn-plain colored text-3xl' },
    ],
    role: ['Machine Learning Engineer'],
    category: ['Data/ML'],
    githubUrl: 'https://github.com/Khaairi/Clothing_Multilabel_Classification',
  },
  {
    name: 'AI-Powered Job Matching Platform with Vector Search',
    date: '2024-07-01',
    description: 'Developed for the Compfest AI Innovation Challenges 2024 Preliminary. An AI-driven platform that simplifies job matching for IT professionals by leveraging vector search and a fine-tuned SBERT model. Features resume upload, real-time job recommendations, and advanced similarity matching.',
    technologies: [
      { name: 'React',                        iconClass: 'devicon-react-original colored text-3xl' },
      { name: 'Docker',                       iconClass: 'devicon-docker-plain colored text-3xl' },
      { name: 'Flask',                        iconClass: 'devicon-flask-original colored text-3xl' },
      { name: 'Google Cloud Platform (GCP)',   iconClass: 'devicon-googlecloud-plain colored text-3xl' },
      { name: 'Python',                       iconClass: 'devicon-python-plain colored text-3xl' },
      { name: 'Numpy',                        iconClass: 'devicon-numpy-plain colored text-3xl' },
      { name: 'Pandas',                       iconClass: 'devicon-pandas-plain colored text-3xl' },
      { name: 'Scikit-Learn',                 iconClass: 'devicon-scikitlearn-plain colored text-3xl' },
    ],
    role: ['Full-Stack Developer', 'Machine Learning Engineer'],
    category: ['Web', 'Data/ML'],
    githubUrl: 'https://github.com/bwbayu/JobFitte',
  },
  {
    name: 'Open Music API',
    date: '2024-07-01',
    description: 'As part of Dicoding AWS Back-End Developer Academy scholarship, this API manages music and playlists using Node.js and AWS. Key features include user authentication with JWT, data export via RabbitMQ, file storage on Amazon S3, and caching with Redis.',
    technologies: [
      { name: 'Node.js',                   iconClass: 'devicon-nodejs-plain-wordmark colored text-3xl' },
      { name: 'JavaScript',                iconClass: 'devicon-javascript-plain colored text-3xl' },
      { name: 'PostgreSQL',                iconClass: 'devicon-postgresql-plain colored text-3xl' },
      { name: 'Amazon Web Services (AWS)', iconClass: 'devicon-amazonwebservices-plain-wordmark colored text-3xl' },
    ],
    role: ['Back-End Developer'],
    category: ['Web'],
    githubUrl: 'https://github.com/bwbayu/openmusic-api',
  },
  {
    name: 'Online Gambling Advertisement Classification',
    date: '2023-09-01',
    description: 'Utilized ResNet-50V2 to classify online gambling advertisements with 98.36% accuracy. By applying data augmentation and fine-tuning, it effectively addressed the growing issue of gambling-related content in digital marketing.',
    technologies: [
      { name: 'Python',       iconClass: 'devicon-python-plain colored text-3xl' },
      { name: 'Numpy',        iconClass: 'devicon-numpy-plain colored text-3xl' },
      { name: 'Pandas',       iconClass: 'devicon-pandas-plain colored text-3xl' },
      { name: 'Scikit-Learn', iconClass: 'devicon-scikitlearn-plain colored text-3xl' },
    ],
    role: ['Machine Learning Engineer'],
    category: ['Data/ML'],
    githubUrl: 'https://github.com/bwbayu/Deep-Learning-Projects/tree/main/Image-Classification/Classification%20of%20online%20gambling%20advertisements',
  },
  {
    name: 'Peer-to-Peer Lending Application',
    date: '2023-02-01',
    description: 'Developed a mobile app using Flutter and FastAPI to connect UMKM with investors. The app features registration, loan tracking, payment systems, and fund management, simplifying access to financial resources and promoting business growth.',
    technologies: [
      { name: 'FastAPI', iconClass: 'devicon-fastapi-plain colored text-3xl' },
      { name: 'SQLite',  iconClass: 'devicon-sqlite-plain colored text-3xl' },
      { name: 'Flutter', iconClass: 'devicon-flutter-plain colored text-3xl' },
    ],
    role: ['Full-Stack Developer'],
    category: ['Mobile'],
    githubUrl: 'https://github.com/bwbayu/P2P_Lending_App_Flutter',
  },
  {
    name: 'Web Based Inventory System',
    date: '2023-02-01',
    description: 'Developed for PT. Husker Anugerah Jaya, this Laravel-based inventory system tracks daily material usage, production output, and sales. It integrates Laravel features like Seeder, Migration, and Eloquent ORM for efficient database management.',
    technologies: [
      { name: 'PHP',     iconClass: 'devicon-php-plain colored text-3xl' },
      { name: 'Laravel', iconClass: 'devicon-laravel-original colored text-3xl' },
      { name: 'MySQL',   iconClass: 'devicon-mysql-original colored text-3xl' },
    ],
    role: ['Full-Stack Developer'],
    category: ['Web'],
    githubUrl: 'https://github.com/bwbayu/Web_Inventaris',
  },
];
