import { Project } from '../../projects/project.type';
import { toSlug } from '../../utils/slug.util';

// Raw projects keep the technology NAMES for readability; they are mapped to skill
// slug ids on export (single source of truth on the skill). Every tech name is a
// verbatim skill name, so toSlug(name) === the seeded skill id.
type RawProject = Omit<Project, 'id' | 'technologies' | 'isShow'> & { technologies: string[] };

const raw: RawProject[] = [
  {
    name: 'StopJudol Youtube Bot',
    date: '2025-09-01',
    description: 'StopJudol is a web dashboard, similar to YouTube Studio, that integrates the YouTube Data API with a fine‑tuned BERT model (~99% accuracy) to automatically detect online‑gambling promotions in YouTube comments. It empowers content creators to clean up their comment sections effortlessly in just two steps: run the detection and bulk-delete flagged comments.',
    technologies: ['Python', 'TypeScript', 'FastAPI', 'React', 'PostgreSQL', 'Redis', 'PyTorch', 'Pandas'],
    role: ['Full-Stack Developer', 'Machine Learning Engineer'],
    category: ['Web', 'ML'],
    githubUrl: 'https://github.com/bwbayu/youtube-bot',
  },
  {
    name: 'Qlassroom',
    date: '2025-09-01',
    description: 'A multi-modal classroom assistant that captures speech, video, slides, images, and documents together into a searchable knowledge memory. Awarded in Qdrant Hackathon 2025 Project by YHHA (Best in Category TwelveLabs)',
    technologies: ['Python', 'Google Cloud Platform (GCP)', 'Cognee', 'Qdrant', 'TwelveLabs', 'CrewAI', 'Gradio'],
    role: ['AI Engineer'],
    category: ['Web', 'ML'],
    githubUrl: 'https://github.com/bwbayu/Qlassroom',
  },
  {
    name: 'RAG Chatbot CSE UPI',
    date: '2025-08-01',
    description: 'A lightweight RAG-based chatbot built with FastAPI and Streamlit to answer questions about the Faculty of Computer Science Education at UPI, using content sourced from the official website.',
    technologies: ['FastAPI', 'Python', 'Docker', 'Google Cloud Platform (GCP)', 'LangChain', 'Pinecone', 'Streamlit'],
    role: ['Full-Stack Developer', 'Machine Learning Engineer'],
    category: ['Web', 'ML'],
    url:       'https://chatbot-upi.bwbayu.space/',
    githubUrl: 'https://github.com/bwbayu/RAG_Chatbot',
  },
  {
    name: 'Thesis Code - ASAS Model Development & Demo Web',
    date: '2025-01-01',
    description: 'A full-stack project for developing and deploying an Automatic Short Answer Scoring (ASAS) system using BERT-based models, combining machine learning experimentation with a web-based demo interface.',
    technologies: ['PyTorch', 'Python', 'Numpy', 'Pandas', 'React', 'Docker', 'Flask', 'Google Cloud Platform (GCP)'],
    role: ['Full-Stack Developer', 'Machine Learning Engineer'],
    category: ['Web', 'ML'],
    url:       'https://asas-demo.web.app/',
    githubUrl: 'https://github.com/bwbayu/thesis-code',
  },
  {
    name: 'KostHub',
    date: '2025-02-01',
    description: 'Participated as Machine Learning Engineer in Mapid WebGIS Competition 2025. Built a price prediction model (XGBoost, R² = 0.82) and a boarding house recommender system (KNN). Deployed models into the system using FastAPI.',
    technologies: ['FastAPI', 'Python', 'Numpy', 'Pandas', 'Scikit-Learn'],
    role: ['Machine Learning Engineer'],
    category: ['Data/ML'],
  },
  {
    name: 'Jenkins Pipeline',
    date: '2025-01-01',
    description: 'Part of the Dicoding IDCamp DevOps Engineer scholarship, where I implemented a CI/CD pipeline using Jenkins, Docker, and AWS EC2 to automate the build, test, and deployment process for a React and Python app. Additionally, integrated Prometheus and Grafana for real-time monitoring and visualization of metrics.',
    technologies: ['Amazon Web Services (AWS)', 'Docker', 'Jenkins', 'Prometheus', 'Grafana'],
    role: ['DevOps Engineer'],
    category: ['Web'],
    githubUrl: 'https://github.com/bwbayu/jenkins-pipeline',
  },
  {
    name: 'Forum API',
    date: '2024-10-01',
    description: 'Part of Dicoding AWS Back-End Developer Academy scholarship, this API was designed for a discussion platform using Clean Architecture and TDD. Features unit, integration, and functional testing, CI/CD with GitHub Actions, and secure deployment on AWS.',
    technologies: ['Amazon Web Services (AWS)', 'PostgreSQL', 'Node.js', 'JavaScript'],
    role: ['Back-End Developer'],
    category: ['Web'],
    githubUrl: 'https://github.com/bwbayu/forum-api',
  },
  {
    name: 'Product Clustering and Recommendation System',
    date: '2024-11-01',
    description: 'Developed for the Hology Data Mining 2024 Final. Using TF-IDF, SentenceTransformer, and POS tagging, improved product discoverability by clustering over 516 categories and building a recommendation system to enhance user experience.',
    technologies: ['Python', 'Numpy', 'Pandas', 'Scikit-Learn'],
    role: ['Data Scientist'],
    category: ['Data/ML'],
    githubUrl: 'https://github.com/bwbayu/product_name_clustering',
  },
  {
    name: 'Clothing Multi-Label Classification',
    date: '2024-10-01',
    description: 'Developed for the Hology Data Mining 2024 Preliminary. Fine-tuned a Vision Transformer (ViT) for multi-label classification to predict clothing type and color. Achieved an Exact Match Ratio (EMR) of 0.9829, securing a top-8 position out of 196 teams.',
    technologies: ['PyTorch', 'Python', 'Numpy', 'Pandas', 'Scikit-Learn'],
    role: ['Machine Learning Engineer'],
    category: ['Data/ML'],
    githubUrl: 'https://github.com/Khaairi/Clothing_Multilabel_Classification',
  },
  {
    name: 'AI-Powered Job Matching Platform with Vector Search',
    date: '2024-07-01',
    description: 'Developed for the Compfest AI Innovation Challenges 2024 Preliminary. An AI-driven platform that simplifies job matching for IT professionals by leveraging vector search and a fine-tuned SBERT model. Features resume upload, real-time job recommendations, and advanced similarity matching.',
    technologies: ['React', 'Docker', 'Flask', 'Google Cloud Platform (GCP)', 'Python', 'Numpy', 'Pandas', 'Scikit-Learn'],
    role: ['Full-Stack Developer', 'Machine Learning Engineer'],
    category: ['Web', 'Data/ML'],
    githubUrl: 'https://github.com/bwbayu/JobFitte',
  },
  {
    name: 'Open Music API',
    date: '2024-07-01',
    description: 'As part of Dicoding AWS Back-End Developer Academy scholarship, this API manages music and playlists using Node.js and AWS. Key features include user authentication with JWT, data export via RabbitMQ, file storage on Amazon S3, and caching with Redis.',
    technologies: ['Node.js', 'JavaScript', 'PostgreSQL', 'Amazon Web Services (AWS)'],
    role: ['Back-End Developer'],
    category: ['Web'],
    githubUrl: 'https://github.com/bwbayu/openmusic-api',
  },
  {
    name: 'Online Gambling Advertisement Classification',
    date: '2023-09-01',
    description: 'Utilized ResNet-50V2 to classify online gambling advertisements with 98.36% accuracy. By applying data augmentation and fine-tuning, it effectively addressed the growing issue of gambling-related content in digital marketing.',
    technologies: ['Python', 'Numpy', 'Pandas', 'Scikit-Learn'],
    role: ['Machine Learning Engineer'],
    category: ['Data/ML'],
    githubUrl: 'https://github.com/bwbayu/Deep-Learning-Projects/tree/main/Image-Classification/Classification%20of%20online%20gambling%20advertisements',
  },
  {
    name: 'Peer-to-Peer Lending Application',
    date: '2023-02-01',
    description: 'Developed a mobile app using Flutter and FastAPI to connect UMKM with investors. The app features registration, loan tracking, payment systems, and fund management, simplifying access to financial resources and promoting business growth.',
    technologies: ['FastAPI', 'SQLite', 'Flutter'],
    role: ['Full-Stack Developer'],
    category: ['Mobile'],
    githubUrl: 'https://github.com/bwbayu/P2P_Lending_App_Flutter',
  },
  {
    name: 'Web Based Inventory System',
    date: '2023-02-01',
    description: 'Developed for PT. Husker Anugerah Jaya, this Laravel-based inventory system tracks daily material usage, production output, and sales. It integrates Laravel features like Seeder, Migration, and Eloquent ORM for efficient database management.',
    technologies: ['PHP', 'Laravel', 'MySQL'],
    role: ['Full-Stack Developer'],
    category: ['Web'],
    githubUrl: 'https://github.com/bwbayu/Web_Inventaris',
  },
];

export const projectsSeed: Omit<Project, 'id'>[] = raw.map(p => ({
  ...p,
  technologies: p.technologies.map(toSlug),
  isShow: true,
}));
